spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.109.49.39:3306/TITAN01
    username: root
    password: WJY20011219
  application:
    name: bussiness
  mvc:
    dispatch-options-request: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
