spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.109.49.39:3306/TITAN01
    username: root
    password: WJY20011219
  application:
    name: bussiness
  mvc:
    dispatch-options-request: true
    throw-exception-if-no-handler-found: true
  redis:
    open: true
    database: 0
    host: 47.109.49.39
    password: WJY20011219
    timeout: 6000ms
    port: 6379
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
